id = "stylus"
name = "Stylus"
version = "0.6.1"
schema_version = 1
authors = ["WMikhail"]
description = "Stylus language support with Tree-sitter semantics, navigation, refactoring, completion, and diagnostics"
repository = "https://github.com/WMikhail/stylus-tooling"
languages = ["languages/stylus"]
snippets = ["./snippets/stylus.json"]

[lib]
kind = "Rust"
version = "0.7.0"

[language_servers.stylus-language-server]
language = "Stylus"
languages = ["Stylus", "Vue.js", "Svelte", "Astro"]

[language_servers.stylus-language-server.language_ids]
Stylus = "stylus"
"Vue.js" = "vue"
Svelte = "svelte"
Astro = "astro"

[grammars.stylus]
repository = "https://github.com/WMikhail/tree-sitter-stylus"
rev = "223a44d8c66ebc07a3f5c7bec76efc257f2d61dd"
